ControlClick("Open","","Edit1")
Sleep(3000)
ControlSetText("Open","","Edit1","C:\Users\Shree\Desktop\WCSA4 WORKSPACE\wcsa4seleniumproject\ScreenShot\ScreenShot1.jpg")
Sleep(3000)
ControlClick("Open","&Open","Button1")
